val = "hello world"
print(f"val: {val}")
print(f"val: {val[0]}")
print(f"slicing ..............")
print(f"val[6:11]: {val[6:11]}")
print(f"val[-1]: {val[-1]}")
print(f"val[6:11:2]: {val[6:11:2]}")
print(f"reverse of val: {val[::-1]}")
print(f"length of val: {len(val)}")
print(f"val[1::-1]: {val[1::-1]}")